/**
 * OpenRAIL-M Attachment A (e)항 의무: Supertonic 음성을 사용한 영상은
 * AI 생성임을 명시(disclaim)해야 한다. `/publish-kit`은 영상 설명과
 * 엔드 카드에 아래 텍스트를 자동으로 포함해야 한다.
 *
 * 이 상수를 단일 소스로 삼아 publish-kit이 직접 참조하도록 한다 —
 * 라이선스 문구를 슬래시 커맨드 프롬프트 안에 자유 형식으로 박지 말 것.
 */

export const AI_VOICE_DISCLAIMER_KO =
  "이 영상의 내레이션은 AI 음성 합성(Supertonic)으로 제작되었습니다.";

export const AI_VOICE_DISCLAIMER_EN =
  "Narration generated by AI voice synthesis (Supertonic).";

export const AI_VOICE_DISCLAIMER_LICENSE_NOTE =
  "음성 합성 모델은 OpenRAIL-M 라이선스에 따라 사용되었으며, 모델의 use-based restrictions를 준수합니다.";

/**
 * 이모지 에셋은 CC BY 4.0 — OpenRAIL-M처럼 attribution이 **법적 의무**다(stock의 "예의"와 다름).
 * 영상이 해당 컴포넌트를 *실제로 쓴 경우에만* /publish-kit이 description + credits.txt에 부착한다:
 *   - DecisionMatrix(정적 마커) → Twemoji
 *   - ReactionBeat(애니메이션 이모지) → Google Noto animated emoji
 * 짧으므로 5000자 캡에서도 트리밍 금지(의무). 단일 소스 — 프롬프트에 자유 형식으로 박지 말 것.
 */
export const EMOJI_ATTRIBUTION_TWEMOJI =
  "이모지 그래픽: Twemoji © Twitter, Inc. 및 기여자, CC BY 4.0 (https://github.com/jdecked/twemoji).";

export const EMOJI_ATTRIBUTION_NOTO =
  "애니메이션 이모지: Noto Emoji © Google, CC BY 4.0 (https://github.com/googlefonts/noto-emoji).";
